# Generated by Django 4.1.7 on 2023-08-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='duplication_count',
        ),
    ]
