# Generated by Django 4.1.7 on 2023-08-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_offer_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='final_price',
        ),
    ]
