# Generated by Django 4.1.7 on 2023-08-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_cartitem_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
